const menuList=[
    {
        title:"Banner",
        key:"/",
        icon:"home"
    },
    {
        title:"教师和菜品",
        key:"/products",
        icon:"appstore",
        children:[
            {
                title:"教师",
                key:"/category",
                icon:"bars"
            },
            {
                title:"菜品",
                key:"/product",
                icon:"tool"
            }
        ]
    },
    {
        title:"用户管理",
        key:"/user",
        icon:"user"
    },
    {
        title:"角色管理",
        key:"/role",
        icon:"safety"
    },
    {
        title:"图形图标",
        key:"/charts",
        icon:"area-chart",
        children:[
            {
                title:"柱状图",
                key:"/charts/bar",
                icon:"bar-chart"
            },
            {
                title:"折线图",
                key:"/charts/line",
                icon:"line-chart"
            },
            {
                title:"饼图",
                key:"/charts/pie",
                icon:"pie-chart"
            }
        ]
    }
]
export default menuList;